Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # Aliases:
        #   - app-static-dev.sunnyrewards.com
        Origins:
          - DomainName: "public-qa-helios.s3.us-east-2.amazonaws.com"
            Id: static-hosting
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: "true"
        HttpVersion: http2
        # ViewerCertificate:
        #   AcmCertificateArn: "arn:aws:acm:us-east-1:Id-of-IAM-User:certificate/1xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx"
        #   MinimumProtocolVersion: TLSv1.2_2021
        #   SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: static-hosting
          ViewerProtocolPolicy: https-only
          Compress: true
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"  # Managed-CachingOptimized
        Logging:
          Bucket: public-qa-logs.s3.us-east-2.amazonaws.com
          IncludeCookies: false
          Prefix: "qa/"

        PriceClass: "PriceClass_All"  # Use all edge locations (best performance)

        
