name: copy static assets
on:
  workflow_dispatch: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      Qapublicbucket: "public-qa"
      Qaplubliclogsbucket: "publ-qa-log"
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: Configure AWS CLI
        run: aws configure set default.region us-east-2

      - name: Get AWS account ID
        id: aws_account_id
        run: |
          aws_account_id=$(aws sts get-caller-identity --query "Account" --output text)
          echo "::set-output name=account_id::$aws_account_id" 

      - name: S3 bucket creation
        run: |
          # if aws s3api head-bucket --bucket ${{ env.Qapublicbucket }} 2>/dev/null; then
          #   echo "Bucket exists."
          # else
          #   echo "Bucket does not exist. Creating"
          #   aws s3api create-bucket --bucket ${{ env.Qapublicbucket }} --create-bucket-configuration LocationConstraint=us-east-2
          #   aws s3api wait bucket-exists --bucket ${{ env.Qapublicbucket }}
            
          #   aws s3api put-public-access-block --bucket ${{ env.Qapublicbucket }} --public-access-block-configuration "BlockPublicAcls=false"
          #   aws s3api put-object --bucket ${{ env.Qapublicbucket }} --key assets/
          # fi    
          # aws s3api put-bucket-policy --bucket ${{ env.Qapublicbucket }} --policy file://s3bucketpolicy.json
          # aws s3 cp .github/workflows/ s3://${{ env.Qapublicbucket }}/assets/ --recursive
          # aws s3 sync .github/workflows/ s3://${{ env.Qapublicbucket }}/assets/ --delete
          
          aws s3api create-bucket --bucket ${{ env.Qapublicbucket }} --object-ownership BucketOwnerPreferred --create-bucket-configuration LocationConstraint=us-east-2
          aws s3api wait bucket-exists --bucket ${{ env.Qaplubliclogsbucket }}
   

          aws cloudformation create-stack \
            --template-body file://cloudfront.yaml \
            --stack-name cloudfront-$GITHUB_RUN_ID
          aws cloudformation wait stack-create-complete --stack-name cloudfront-$GITHUB_RUN_ID
